data:
  raw: ../data/raw/file20.csv
  processed: ../data/processed/clean_data_knn_rf_minmax.csv
  norm_params: data/processed/norm_params.json
  forecasts: data/forecasts/forecasts.csv
  column_mapping:
    time_dt: time_dt
    group: uuid
    target: A_plus

preprocessing:
  target_column: A_plus
  period: 24
  miss_method: knn  # 'linear', 'seasonal', 'knn'
  anom_method: iqr  # 'rf' или 'stl' или 'mixed' iqr
  anom_act: interpolate
  norm_method: log  # 'minmax', 'log', 'user_minmax'
  k: 5
  thresh: 4.0
  rf_n_estimators: 150
  lookback: 168
  process_missing: true
  process_anomalies: true
  process_normalization: true

forecasting:
  model: nbeats  # Можно выбрать arima, nbeats, xgboost
  horizon: 168
  horizons: [72, 96, 120, 144, 168]  # Горизонты для кросс-валидации
  arima:
    order: [2, 0, 1]
    auto: true
    s: 24
  nbeats:
    num_stacks: 2
    num_blocks: 3
    num_layers: 4
    layer_widths: 512
    n_epochs: 50
  xgboost:
    num_boost_round: 400
    max_depth: 6
    learning_rate: 0.1
    gamma: 0.1
    lambda: 2
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 3
    early_stopping_rounds: 10

graphics:
  output_dir: graphics

logging:
  log_file: logs/project.log