data:
  raw: ../data/raw/file20.csv
  processed: ../data/processed/clean_data_knn_rf_minmax.csv
  norm_params: data/processed/norm_params.json
  forecasts: data/forecasts/forecasts.csv
  column_mapping:
    time_dt: time_dt
    group: uuid
    target: A_plus

preprocessing:
  target_column: A_plus
  period: 24
  miss_method: knn  # 'linear', 'seasonal', 'knn'
  anom_method: iqr  # 'rf' или 'stl' или 'mixed' iqr
  anom_act: interpolate
  norm_method: log  # 'minmax', 'log', 'user_minmax'
  k: 5
  thresh: 4.0
  rf_n_estimators: 150
  lookback: 168
  seasonal_period : 24 # 168 / 720
  acf_pacf_lags : 720
  process_missing: true
  process_anomalies: true
  process_normalization: true

forecasting:
  model: nbeats  # Можно выбрать arima, nbeats, xgboost
  horizon: 168
  horizons: [168, 360]  # Для кросс-валидации
  final_horizon: 720  # Финальный прогноз на месяц
  recursive_steps: 4  # 4 недели для месяца
  nbeats:
    num_stacks: 2
    num_blocks: 3
    num_layers: 4
    layer_widths: 512
    n_epochs: 50
  arima:
    order: [1, 0, 1]
    auto: true
    s: 24
  xgboost:
    num_boost_round: 300
    max_depth: 10 # 9-10
    learning_rate: 0.03 # 0.02–0.04
    gamma: 0.005
    lambda: 3
    subsample: 0.87
    colsample_bytree: 0.85
    min_child_weight: 3
    early_stopping_rounds: 20

graphics:
  output_dir: graphics

logging:
  log_file: logs/project.log